---
- hosts: server
  user: ec2-user
  become: yes
  connection: ssh
  tasks:
    - name: "Install specified python requirements"
      pip:
      	virtualenv: /var/www/html/django
     	requirements: requirement.txt
    - name: restart apache
      shell: /usr/local/apache2/bin/apachectl restart

