---
- hosts: server
  user: ec2-user
  become: yes
  connection: ssh
  tasks:
    - name: "Install specified python requirements"
      pip:
          virtualenv: /var/www/html/django/.py3env
          requirements: requirement.txt
          chdir: /var/www/html/django/project/
    - name: restart apache
      shell: /usr/local/apache2/bin/apachectl restart

