---
- hosts: server
  user: ec2-user
  become: yes
  connection: ssh
  tasks:
    - name: Install specified python requirements
      ansible.builtin.pip:
      virtualenv: /var/www/html/django
      virtualenv_command: source .py3env/bin/activate
    - name: restart apache
      shell: /usr/local/apache2/bin/apachectl restart

